# Generated by Django 2.2.6 on 2019-10-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default='Null_Course', max_length=50),
        ),
    ]
