# Generated by Django 2.2.6 on 2019-10-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191015_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='add in later', max_length=50),
        ),
    ]
