# Generated by Django 2.2.6 on 2019-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='Newton', max_length=50),
        ),
    ]
