# Generated by Django 2.2.5 on 2019-09-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190924_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='last_login_date',
        ),
    ]
