# Generated by Django 2.2.5 on 2019-10-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_butt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Butt',
        ),
    ]
