# Generated by Django 2.2.5 on 2019-11-19 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'exam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField(blank=True, null=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exam')),
            ],
            options={
                'db_table': 'multiple_choice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_grade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_exam', models.ManyToManyField(blank=True, to='examination.exam')),
                ('student', models.ManyToManyField(related_name='_coursecourse_student_+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_course',
                'managed': True,
            },
        ),
    ]
