# Generated by Django 2.0.7 on 2019-10-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
    ]
