# Generated by Django 2.2.5 on 2019-10-22 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecourse',
            name='student',
            field=models.ManyToManyField(related_name='_coursecourse_student_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
