# Generated by Django 2.2.5 on 2019-11-13 23:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='potential_answer',
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='potential_answer',
            field=multiselectfield.db.fields.MultiSelectField(default='value', max_length=200),
            preserve_default=False,
        ),
    ]
