# Generated by Django 2.2.5 on 2019-10-22 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_coursecourse_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
