# Generated by Django 2.2.6 on 2019-10-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20191015_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.CharField(default='dummy course', max_length=50),
        ),
    ]
