# Generated by Django 2.2.5 on 2019-11-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20191113_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='potential_answer',
        ),
        migrations.AddField(
            model_name='potentialanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examination.MultipleChoice'),
            preserve_default=False,
        ),
    ]
