# Generated by Django 2.2.6 on 2019-10-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20191015_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
