# Generated by Django 2.2.5 on 2019-10-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_question_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
