# Generated by Django 2.0.7 on 2019-10-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tests',
            new_name='exam',
        ),
    ]
