# Generated by Django 2.2.5 on 2019-11-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191029_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exam',
        ),
    ]
