# Generated by Django 2.2.6 on 2019-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='s', max_length=1),
            preserve_default=False,
        ),
    ]
